version: 0.2

env:
  secrets-manager:
    AES_KEY: "cex/secret:aes-key"
    AWS_ACCESS_KEY_ID: "cex/secret:aws_access_key_id"
    AWS_SECRET_ACCESS_KEY: "cex/secret:aws_secret_access_key"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 006852863024.dkr.ecr.ap-northeast-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t testsecret . --build-arg="AES_KEY=$AES_KEY"
      - docker tag testsecret:latest 006852863024.dkr.ecr.ap-northeast-1.amazonaws.com/testsecret:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 006852863024.dkr.ecr.ap-northeast-1.amazonaws.com/testsecret:latest
